version: "3.7"
services:

  traefik:
    image: traefik:alpine
    command:
      - "--entrypoints=Name:http Address::80"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--logLevel=debug"
      - "--api"
      - "--ping"
      - "--ping.entrypoint=http"
      - "--docker"
      - "--docker.swarmmode"
      - "--docker.domain=swarm.mydomain.com"
      - "--docker.watch"
      - "--acme"
      - "--acme.storage=acme.json"
      - "--acme.email=admin@mydomain.com"
      - "--acme.entrypoint=https"
      - "--acme.httpchallenge.entrypoint=http"
      - "--acme.onhostrule=true"
    networks:
      - core
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role==manager]
 
  portainer:
    image: portainer/portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainerdata:/data"
    networks:
      - core
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.port=9000"
        - "traefik.docker.network=traefik-services_core"
        - "traefik.frontend.rule=Host:admin.swarm.mydomain.com"

  demo: # FOR DEMO PURPOSES ONLY, FEEL FREE TO REMOVE
    image: nginxdemos/hello
    networks:
      - core
    deploy:
      replicas: 3
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-services_core"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:swarm.mydomain.com"

networks:
  core:
    driver: overlay
    driver_opts:
      encrypted: 1
 
volumes:
  portainerdata: